In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
path = '/home/antoni/PycharmProjects/JupyterProjects/Coursera: ML : Regression/KCData/kc_house_train_data.csv'
path_test = '/home/antoni/PycharmProjects/JupyterProjects/Coursera: ML : Regression/KCData/kc_house_test_data.csv'
df = pd.read_csv(path)
df_test = pd.read_csv(path_test)

Directions
---------- -----------------

Next write a function that takes a data set, a list of features (e.g. [‘sqft_living’, ‘bedrooms’]), to be used as inputs, and a name of the output (e.g. ‘price’). This function should return a features_matrix (2D array) consisting of first a column of ones followed by columns containing the values of the input features in the data set in the same order as the input list. It should also return an output_array which is an array of the values of the output in the data set (e.g. ‘price’). e.g. if you’re using SFrames and numpy you can complete the following function:


In [2]:
def get_numpy_data(df, features, output):
    inputs = df[features]
    features_matrix = inputs.values
    a = np.ones((len(df.index),1))
    features_matrix = np.concatenate([np.ones((len(df.index),1)) ,features_matrix], axis=1)
    output_array = output.values
    return(features_matrix, output_array)

In [3]:
X = df.drop(columns = 'price')
y = df.price

In [4]:
get_numpy_data(X, ['bedrooms'], y)

(array([[1., 3.],
        [1., 3.],
        [1., 2.],
        ...,
        [1., 3.],
        [1., 3.],
        [1., 2.]]),
 array([221900., 538000., 180000., ..., 360000., 400000., 325000.]))

Directions
------------- -------
If the features matrix (including a column of 1s for the constant) is stored as a 2D array (or matrix) and the regression weights are stored as a 1D array then the predicted output is just the dot product between the features matrix and the weights (with the weights on the right). Write a function ‘predict_output’ which accepts a 2D array ‘feature_matrix’ and a 1D array ‘weights’ and returns a 1D array ‘predictions’. e.g. in python:

In [5]:
def predict_outcome(feature_matrix, weights):
    predictions = np.dot(feature_matrix, weights)
    return (predictions)

Directions
----------- --

If we have a the values of a single input feature in an array ‘feature’ and the prediction ‘errors’ (predictions - output) then the derivative of the regression cost function with respect to the weight of ‘feature’ is just twice the dot product between ‘feature’ and ‘errors’. Write a function that accepts a ‘feature’ array and ‘error’ array and returns the ‘derivative’ (a single number). e.g. in python:
----------- --

We have to remember the result [gradient]RSS(w) = -2 * H[transpose] (y-Hw) = -2 * H[transpose] (error)


In [6]:
def feature_derivative(errors, feature):
    derivative = 2* np.dot(feature, error)
    return(derivative)

In [7]:
a = np.array(((10,20), (4,16)))
print(a.T)

[[10  4]
 [20 16]]


In [8]:
np.sqrt(a)

array([[3.16227766, 4.47213595],
       [2.        , 4.        ]])

Directions
------ -----
Now we will use our predict_output and feature_derivative to write a gradient descent function. Although we can compute the derivative for all the features simultaneously (the gradient) we will explicitly loop over the features individually for simplicity. Write a gradient descent function that does the following:

Accepts a numpy feature_matrix 2D array, a 1D output array, an array of initial weights, a step size and a convergence tolerance.

While not converged updates each feature weight by subtracting the step size times the derivative for that feature given the current weights

At each step computes the magnitude/length of the gradient (square root of the sum of squared components)

When the magnitude of the gradient is smaller than the input tolerance returns the final weight vector.


The above was a top down attempt. We need to start from smalle elements, test them and then add them together. The first element we need is getting the partial derivative for all the features. Below is the second unassisted attempt.

Ok so to deal with the gradient we needed the gradient magnitude, a formula for which was given by the course : gradient_magnitude = sqrt(gradient_sum_squares). So below is third attempt with this new information. Its still a vector so I guess toleranc is also a vector?

In [10]:
def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converge = False
    weights = initial_weights
    while converge == False:
        predicted = np.dot(feature_matrix, list(weights))
        error = output - predicted
        gradient = np.ones(((feature_matrix.shape[1]-1),1))
        for i in range(gradient.shape[0]):
            for feature in feature_matrix.T:
                partial = 2 * np.dot(feature.T, error)
                gradient[i] = partial
        gradient_magnitude = np.sqrt(gradient)
        if (gradient_magnitude < tolerance).all():
            converge = True
            return weights
        else:
            weights += (step_size * gradient.T)[0]
            print(weights)

Test
--- ---
Below will be a little test ot this gradient descent algorithm

In [11]:
X = df.drop(columns = 'price')
y = df.price
simple_features = ['sqft_living']
output_col= ['price']
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7

In [12]:
my_feature_matrix = get_numpy_data(X, ['sqft_living'], y)[0]
my_output = get_numpy_data(X, ['sqft_living'], y)[1]

So we ended up running to the problem we predicted.

In [33]:
def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converge = False
    weights = initial_weights
    while converge == False:
        predicted = np.dot(feature_matrix, list(weights))
        error = output - predicted
        gradient = np.ones(((feature_matrix.shape[1]-1),1))
        for i in range(gradient.shape[0]):
            for feature in feature_matrix.T:
                partial = 2 * np.dot(feature.T, error)
                gradient[i] = partial
        gradient_magnitude = np.sqrt(gradient)
        if (gradient_magnitude < tolerance).all():
            converge = True
            return weights
        else:
            weights += (step_size * gradient.T)[0]

In [14]:
X = df.drop(columns = 'price')
y = df.price
simple_features = ['sqft_living']
output_col= ['price']
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7
my_feature_matrix = get_numpy_data(X, ['sqft_living'], y)[0]
my_output = get_numpy_data(X, ['sqft_living'], y)[1]

In [15]:
error = my_output - np.dot(my_feature_matrix, initial_weights)
print(error, my_output)

[267720. 582430. 226230. ... 405470. 445400. 370980.] [221900. 538000. 180000. ... 360000. 400000. 325000.]


In [16]:
for feature in my_feature_matrix.T:
    partial = 2 * np.dot(feature.T, error)

In [17]:
gradient = np.ones(((my_feature_matrix.shape[1]-1),1))
for i in range(gradient.shape[0]):
    for feature in my_feature_matrix.T:
        partial = 2 * np.dot(feature.T, error)
        gradient[i] = partial

In [18]:
print (partial)

50551526703218.0


In [19]:
print(gradient)

[[5.05515267e+13]]


In [20]:

gradient = np.ones((my_feature_matrix.shape[1], 1))
print(gradient)

[[1.]
 [1.]]


In [34]:
regression_gradient_descent(my_feature_matrix, my_output, initial_weights, step_size, 2.5e5)

array([-46719.28777939,    281.71222061])

In [24]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
f = pd.DataFrame(X['sqft_living'])
lr.fit(f, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [25]:
lr.intercept_

-47116.07907289371

In [26]:
lr.coef_

array([281.95883963])